spring:
  application:
    name: shop
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.shop.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.shop.mapper: debug