-- 테스트 데이터 

INSERT INTO CATEGORY (CTGRY_NO, CTGRY_NM)
VALUES (SEQ_CTGRY_NO.NEXTVAL, '상의');

INSERT INTO PRODUCT (PRD_NO, CTGRY_NO, PRD_NM, ORGNL_PRC, SALE_PRC)
VALUES (SEQ_PRD_NO.NEXTVAL, 1, '기본 티셔츠', 29000, 19000);

INSERT INTO PRODUCT (PRD_NO, CTGRY_NO, PRD_NM, ORGNL_PRC, SALE_PRC)
VALUES (SEQ_PRD_NO.NEXTVAL, 1, '오버핏 맨투맨', 59000, 42000);

